### PR TITLE
Fix IDEA freeze

### LINKED ISSUE #93: IDE freezes
### Bug Description

Almost always when I try to run my application with mirrord my IDE just freezes until I kill it.

I use the default settings + define the target deployment and namespace.

thread dump is attached
[mirrord_freeze.zip](https://github.com/metalbear-co/mirrord-intellij/files/12408536/mirrord_freeze.zip)

### Steps to Reproduce

1. Enable mirrord
2. Run application (in my case a Java Spring Boot app)
3.  The last log message then reads `INFO - mirrord - running mirrord with following command line: /usr/local/bin/mirrord ext -f /some/path/mirrord.json`

### Backtrace

_No response_

### Relevant Logs

_No response_

### Your operating system and version

Ubuntu 22.04.2 LTS, Intellij Idea Ultimate 2023.2, mirrord plugin 3.52.0

### Local process

/snap/bin/intellij-idea-ultimate

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by Razz4780**
Closes #93

### CODE REVIEW

File: modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt [hunk 1]
```diff
@@ -241,13 +241,17 @@ class MirrordApi(private val service: MirrordProjectService) {
...
-            return environment.get(30, TimeUnit.SECONDS)
+            return environment.get(2, TimeUnit.MINUTES)
         } catch (e: Throwable) {
             logger.debug("failed to fetch the env", e)
 
-            val processStdError = process.errorStream.reader().readText()
-            if (processStdError.startsWith("Error: ")) {
-                throw MirrordError.fromStdErr(processStdError)
+            if (process.isAlive) {
+                process.destroyForcibly()
```
Comment (aviramha) [inline modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt:249]: log warning

Comment (aviramha) [reply modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt:249]: I think destroy is good enough

File: modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt [hunk 2]
```diff
@@ -241,13 +241,17 @@ class MirrordApi(private val service: MirrordProjectService) {
         ProgressManager.getInstance().run(mirrordProgressTask)
 
         try {
-            return environment.get(30, TimeUnit.SECONDS)
+            return environment.get(2, TimeUnit.MINUTES)
         } catch (e: Throwable) {
             logger.debug("failed to fetch the env", e)
```
Comment (aviramha) [inline modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt:246]: logger.error - Running mirrord failed?

File: modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt [hunk 3]
```diff
@@ -241,13 +241,17 @@ class MirrordApi(private val service: MirrordProjectService) {
...
+            if (process.isAlive) {
+                process.destroyForcibly()
+            } else {
+                val processStdError = process.errorStream.reader().readText()
+                if (processStdError.startsWith("Error: ")) {
+                    throw MirrordError.fromStdErr(processStdError)
+                }
             }
 
             throw MirrordError("failed to fetch the env", e)
```
Comment (aviramha) [inline modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt:257]: Running mirrord failed

**Review by aviramha — APPROVED** [review]

**Comment by aviramha** [comment]
Great job!
